### ISSUE TITLE
black screen launch

### ISSUE THREAD

**Issue by jonbro** [XK9274/pico-8-wrapper-miyoo#1]
I'm having an issue on the 0.8 release where it is launching into a black screen. I hear the pico-8 startup chime first though. Before I change anything about my device, is there something I could do to help debug this issue?

none of the hotkeys seem to have a visual effect (I don't see any bezels when doing the bezel switch hot key for example).

**Comment by jonbro** [comment]
Actually - I'm on a RC for onion OS 4.2.0, so I'm going to upgrade that first and reopen this if I can get the error to occur again.

**Comment by jonbro** [comment]
Ok, I upgraded to 4.2.3, and I'm still getting this issue, so I'm reopening.

**Comment by XK9274** [comment]
> Ok, I upgraded to 4.2.3, and I'm still getting this issue, so I'm reopening.

Can you copy the `config.txt` file from a new downloaded archive into the `/mnt/SDCARD/App/pico/.lexaloffle/pico-8` dir and try again?

![image](https://github.com/XK9274/pico-8-wrapper-miyoo/assets/47260768/43567577-6bd1-4373-8321-ff724393a639)

**Comment by jonbro** [comment]
that fixed it, thank you - I've attached the config.txt as it was before overwriting in case it was something about this file that went sideways.
[config.txt](https://github.com/XK9274/pico-8-wrapper-miyoo/files/13326698/config.txt)

I got it off the SD card just via a windows explorer copy.

**Comment by XK9274** [comment]
![image](https://github.com/XK9274/pico-8-wrapper-miyoo/assets/47260768/b615914a-b76f-4971-aa64-807888826e85)

That's great, enjoy!

Thanks for attaching, btw

This was your problem (window size set to 0, 0)

**Comment by jonbro** [comment]
I'm curious _how_ that got set though - I didn't edit this config.txt at all. I was playing pico-8, and I think I either tried to quit or shutdown, and when I came back to it, this happened on every subsequent run. I'm guessing that pico-8 is writing bad values to this file during its execution somehow, wondering if you think I should report this issue to zep?

**Comment by XK9274** [comment]
I wouldn't bother reporting it to Zep as it may be a waste of his time, i've not personally had this issue but a few people have; so i'll add something into 0.9 to check the values of that config file and re-write them if they're bad, will be a quick execution and you'll probably not even know it's happening.

Will reopen this issue until it's added actually, cheers

**Comment by XK9274** [comment]
Fixed by this function:

https://github.com/XK9274/pico-8-wrapper-miyoo/blob/5f34aca2212d75842dd91319cd6b6d5212eac5d2/pico/script/launch.sh#L103

Which was updated in:

e83b002

And will go live officially in 0.8.2 (But you can download the new launch.sh yourself if needed [here](https://github.com/XK9274/pico-8-wrapper-miyoo/blob/main/pico/script/launch.sh)

mb forgot to add output:

```
Config checker: Validating display settings in config.txt
Added missing setting: window_size
Added missing setting: screen_size
Added missing setting: windowed
Added missing setting: window_position
Added missing setting: frameless
Added missing setting: fullscreen_method
Added missing setting: blit_method
Added missing setting: transform_screen
Updated settings:
window_size 640 480
screen_size 640 480
windowed 0
window_position -1 -1
frameless 1
fullscreen_method 2
blit_method 2
transform_screen 134
```
