### ISSUE TITLE
after sleeping and waking the console, PICO-8 runs about 50% slower

### ISSUE THREAD

**Issue by schoblaska** [XK9274/pico-8-wrapper-miyoo#11]
1. Power on the Miyoo Mini
2. Launch PICO-8
3. Start playing a cart
4. Put the Miyoo to sleep (by tapping the power button)
5. Wake the Miyoo back up (by tapping the power button)
6. PICO-8 now runs about 50% slower

I tried a few other apps / emulators and I can only reproduce this on the PICO-8 wrapper. Let me know if there's anything I can do to help debug!

**Comment by XK9274** [comment]
Heya, this is because the miyoos clock speed reverts back to 600 when the device sleeps and it won't catch another change to performance until MainUI runs most likely. 

You can push the clock back up to something more suitable using: Select + Up/Down.

**Comment by schoblaska** [comment]
Ah, that explains it. Thanks for the explanation!
