### ISSUE TITLE
Future version. Please update!

### ISSUE THREAD

**Issue by dormk23** [XK9274/pico-8-wrapper-miyoo#15]
I'm guessing that there is a new version already available. Is there a way to update it myself? Or should it be compiled into the wrapper?

Thanks !

**Comment by XK9274** [comment]
Aloha,

This is just spore reporting that the cart you're trying to play has been updated/created with a higher version of pico than you currently have. Nothing is required in the wrapper but you'll need to go to the pico8 download page within your lexaloffle account and grab the latest pico8 .dat and .bin files (remember its the Raspberry PI versions) and copy them into your bin directory on your SD card. 

Instructions can be found here https://onionui.github.io/docs/emulators/pico-8-standalone

Cheers!

**Comment by dormk23** [comment]
Thank you so much!! I didn't know that's all I needed to do. It worked!
