### ISSUE TITLE
OG MM and Allium

### ISSUE THREAD

**Issue by axiel7** [XK9274/pico-8-wrapper-miyoo#2]
I'm trying to get this to work with my setup: OG Miyoo Mini with Allium

So far I only had to rename some paths and folders but now I'm getting this error at launch:
```
pico8_dyn: error while loading shared libraries: libfreetype.so.6: cannot open shared object file: No such file or directory
```

Any idea what is this lib? Maybe it's a lib that's included in Onion but not on Allium?

[Full log](https://github.com/XK9274/pico-8-wrapper-miyoo/files/13327360/pico.log)

**Comment by XK9274** [comment]
Hi sorry i don't have any cards with allium on atm. 

You'll be using the same firmware though, so if you'll need to set your LD_LIBRARY_PATH in the launch script to include the location:

`/customer/lib/libfreetype.so.6`

It will look something like this:

`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/customer/lib`

**Comment by axiel7** [comment]
It seems I was missing the `/mnt/SDCARD/miyoo` folder (I think because I was in an old fw) that contains some required libs.

After upgrading the fw and putting the `miyoo` folder now I get another missing lib:

```
pico8_dyn: error while loading shared libraries: libpng16.so.16: cannot open shared object file: No such file or directory
```
I tried exporting `/customer/lib` as you said with no luck.

Has been this tested in the OG Miyoo Mini (not the plus)? I'm starting to think this is not compatible with the OG.

[Full log](https://github.com/XK9274/pico-8-wrapper-miyoo/files/13329803/pico.log)

**Comment by XK9274** [comment]
Works fine on the OG mini. You're missing libraries or library paths in allium.

**Comment by axiel7** [comment]
> Works fine on the OG mini

Thanks for clarifying

> You're missing libraries or library paths in allium.

Does your `miyoo` folder contain the `libpng16.so.16` lib? I tried looking for that lib in the root filesystem but I couldn't find it and the [official firmware](https://app.sugarsync.com/iris/wf/D4978471_09235444_474129#cGFnZUlkPXdlYmxpbmtzJmlzV2VibGlua3NGb2xkZXI9dHJ1ZSZpc0l0ZW1SZWZyZXNoQWxsb3dlZD10cnVlJnVzZXJJZD0tMSZjdXJyZW50T3duZXJJZD05NDIzOTI2JmN1cnJlbnRGb2xkZXJJZD01NDc4MDk5OV85NjU1OTgmY3VycmVudEZvbGRlck5hbWU9bWl5b28lMjBtaW5pJTIwdjQlMjAxMDI3JndlYmxpbmtJZD1ENDk3ODQ3MV8wOTIzNTQ0NF80NzQxMjkmdG9rZW5UaW1lPTE2OTk4NjIwMjM3OTAmY3NyZnRva2VuPWEyNDIyY2Y2LTRhNTYtNGFmYS1hMTUzLTVkZTI1NjQ2ZTk5NiZtb2RlPQ==) doesn't have it either.

My guess is that maybe OnionOS adds that lib and maybe others while installing?

**Comment by axiel7** [comment]
Okay I got it working, for reference these are the steps:

1. Follow the instructions from the README.
2. Rename the `/mnt/SDCARD/Apps/pico` folder to `/mnt/SDCARD/Apps/pico-8.pak` so Allium detect it as a program.
3. Modify the file `/mnt/SDCARD/Apps/pico-8.pak/script/launch.sh` so it uses the new path:
```bash
export picodir=/mnt/SDCARD/Apps/pico-8.pak
```
And the mount dir at the end of the file:
```bash
mount --bind /mnt/SDCARD/Roms/PICO /mnt/SDCARD/Apps/pico-8.pak/.lexaloffle/pico-8/carts
start_pico
umount /mnt/SDCARD/Apps/pico-8.pak/.lexaloffle/pico-8/carts
```
**Note:** make sure your pico-8 roms directory is `/mnt/SDCARD/Roms/PICO` and the roms file extensions is .p8.png

4. Modify these two lines in `/mnt/SDCARD/Apps/pico-8.pak/.lexaloffle/pico-8/config.txt` so it uses the new path:
```
// Location of pico-8's root folder
root_path /mnt/SDCARD/Apps/pico-8.pak/.lexaloffle/

// Location of cartridge save data
cdata_path /mnt/SDCARD/Apps/pico-8.pak/.lexaloffle/pico-8/cdata/
```

5. Put this file [libpng16.so.16](https://github.com/OnionUI/Onion/blob/main/static/packages/RApp/SCUMM%20(ScummVM%20standalone)/RApp/scummvm/libpng16.so.16) from the OnionOS ScummVM inside `/mnt/SDCARD/.tmp_update/lib`

**Comment by XK9274** [comment]
Ah good stuff, glad you got it sorted, sorry i couldn't be more help - working long hours atm. 

I think we can leave this issue open for some time as i doubt it's just you who will be trying to get this working on Allium and it's great that it will be supported on other UI.

**Comment by XK9274** [comment]
Closing as added to main README on: 81ca74a

**Comment by goweiwen** [comment]
Thanks for investigating this issue!

I have packaged the required changes here: https://github.com/goweiwen/pico-8-wrapper-miyoo/releases

## Steps
1. Download and extract [pico.pak.zip](https://github.com/goweiwen/pico-8-wrapper-miyoo/releases) to `/Apps`.
2. Put the `pico8_dyn` and `pico8.dat` files into `/Apps/pico.pak/bin` (create the folder if it doesn't exist)
3. Run the `Pico-8` app

If I (or anyone) have time, I will try to get this build to work with both OnionOS and Allium.
