### ISSUE TITLE
Black screen then back to menu

### ISSUE THREAD

**Issue by jonathaninacio** [XK9274/pico-8-wrapper-miyoo#7]
Hi, 
I'm having an issue when launching the wrapper from the menu of the miyoo.
the wrapper seem to launch then I ear a crackle sound, then i have the miyoo menu loading and I'm back to the menu.
I'm on miyoo mini+ FW-202306282128 running OnionOS 4.2.3.

I used the files from the raspberry pi version and had to make the bin folder in App/pico/ to copy them in.

have any idea of where I messed up?

**Comment by yokoboko** [comment]
You should copy them to `App/pico/bin` folder. I made the same mistake.

**Comment by jonathaninacio** [comment]
I tried the whole process again with another sd card reader (not the one that came with the miyoo mini+) and it worked perfectly. 

Sorry for this issue that wasn't one.

**Comment by matthewp** [comment]
This happens to me. You had to get a new sd card?
